import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {chromium,expect} from '@playwright/test';

const app=fileURLToPath(new URL('../..',import.meta.url));
const child=spawn('uv',['run','--locked','--no-editable','--project',app,'--extra','dev','python',fileURLToPath(new URL('./serve_extraction.py',import.meta.url))],{env:{...process.env,PYTHONPATH:resolve(app,'src')},stdio:['ignore','pipe','pipe']});
let log='',browser;
child.stdout.on('data',v=>log+=v);child.stderr.on('data',v=>log+=v);
try{
  let base;for(let i=0;i<300;i++){base=log.match(/READY (http:\/\/127.0.0.1:\d+)/)?.[1];if(base)break;if(child.exitCode!==null)throw Error(log);await new Promise(r=>setTimeout(r,100));}assert(base,log);
  browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await mkdir(resolve('.qa/extraction-ui'),{recursive:true});
  await page.goto(base+'/ai');
  await expect(page.locator('[data-scenario="paper"]')).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('.ai-paper-scenario a')).toHaveText('从材料提取知识 · 使用 Codex →');
  await page.screenshot({path:resolve('.qa/extraction-ui/assistant-desktop.png'),fullPage:true});
  await page.locator('.ai-batch-entry').click();
  await expect(page.locator('.studio-maintenance.active')).toHaveAttribute('href','/ai');
  await expect(page.locator('#ex-runtime')).toContainText('已登录');
  await expect(page.locator('#ex-max')).toHaveValue('20');
  await expect(page.locator('#ex-max')).toBeVisible();
  await expect(page.locator('#ex-rules')).not.toHaveAttribute('open','');
  await page.locator('#ex-rules summary').click();
  await expect(page.locator('#ex-knowledge')).toBeVisible();
  await expect(page.locator('#ex-knowledge')).not.toHaveValue('');
  await page.locator('#ex-rules summary').click();
  await page.screenshot({path:resolve('.qa/extraction-ui/empty-desktop.png'),fullPage:true});
  await page.locator('#ex-files').setInputFiles([{name:'one.md',mimeType:'text/markdown',buffer:Buffer.from('# First paper\nSpectral clustering partitions similarity graphs using eigenvectors.\n')},{name:'two.md',mimeType:'text/markdown',buffer:Buffer.from('# Second paper\nSpectral clustering uses graph Laplacian eigenvectors.\n')}]);
  await expect(page.locator('.ex-member')).toHaveCount(2);
  await expect(page.locator('#ex-budget-summary')).toContainText('2 份材料 · 最多新增 20 个知识点');
  await expect(page.locator('#ex-max')).toHaveValue('20');
  const duplicate=page.locator('.ex-member').first().getByLabel('标记为重复材料');
  await expect(duplicate).toBeHidden();
  await page.locator('.ex-member').first().getByText('更多操作',{exact:true}).click();
  await expect(duplicate).toBeVisible();
  await expect(duplicate.locator('option').nth(1)).toContainText('是同一份材料');
  await duplicate.focus();
  await page.waitForResponse(r=>r.url().includes('/api/extraction/')&&r.request().method()==='GET'&&!r.url().endsWith('/runtime'));
  await expect(duplicate).toBeFocused();
  await page.locator('.ex-member').first().getByText('更多操作',{exact:true}).click();
  await expect(duplicate).toBeHidden();
  await expect(page.locator('#ex-start')).toBeEnabled();await page.locator('#ex-start').click();
  await expect(page.locator('#ex-status')).toContainText('等待审核',{timeout:30000});
  await expect(page.locator('#ex-run-budget')).toContainText('最多新增 20 个知识点');
  await expect(page.locator('#ex-budget-results')).toContainText('未报告因数量上限暂缓的概念');
  const taskId=new URL(page.url()).searchParams.get('task');
  assert.equal((await (await page.request.get(base+'/api/extraction/'+taskId)).json()).policy.max_nodes,20);
  await expect(page.locator('.review-item')).toHaveCount(5);
  await page.getByRole('button',{name:'显示图谱',exact:true}).click();
  await expect(page.locator('#graph .node')).toHaveCount(3);
  await expect(page.locator('#graph .edge-group')).toHaveCount(2);
  const mastery=page.locator('.review-inspector select[name="knowledge_level"]');
  await expect(mastery).toBeVisible();await mastery.selectOption('familiar');
  await expect(page.locator('.review-inspector .primary-button')).toBeEnabled();
  await page.screenshot({path:resolve('.qa/extraction-ui/review-desktop.png'),fullPage:true});
  // Selecting only a relation must ask for its missing endpoints before any write.
  await page.locator('.review-item input[type=checkbox]').last().check();
  await page.getByRole('button',{name:'通过所选（1）',exact:true}).click();
  await expect(page.locator('.review-message')).toContainText('请核对后再次点击');
  const before=(await (await page.request.get(base+'/api/extraction/'+taskId)).json()).submissions[0];
  const pending=await (await page.request.get(base+'/api/inbox/v1/items/'+encodeURIComponent('change_set:'+before.change_set_id)+'/review')).json();
  assert(pending.proposals.every(p=>p.status==='pending_review'));
  await page.getByRole('button',{name:'清空选择',exact:true}).click();
  await page.getByRole('button',{name:'选择全部待审核',exact:true}).click();
  await page.getByRole('button',{name:'通过所选（5）',exact:true}).click();
  await expect(page.locator('.review-message')).toContainText('已通过并保存 5 项',{timeout:30000});
  await expect(page.locator('.review-item')).toHaveCount(5);
  const submission=(await (await page.request.get(base+'/api/extraction/'+taskId)).json()).submissions[0];
  const review=(await (await page.request.get(base+'/api/inbox/v1/items/'+encodeURIComponent('change_set:'+submission.change_set_id)+'/review')).json());
  assert(review.proposals.every(p=>['accepted','edited_and_accepted'].includes(p.status)));
  assert.equal(review.proposals.find(p=>p.entity_type==='knowledge_node').values.knowledge_level,'familiar');
  await page.goto(base+'/knowledge');await expect(page.locator('#graph .node')).not.toHaveCount(0);
  await page.goto(base+'/inbox?view=all&item='+encodeURIComponent('change_set:'+submission.change_set_id));
  await expect(page.locator('.review-item')).toHaveCount(5);
  await page.getByRole('button',{name:'显示图谱',exact:true}).click();await expect(page.locator('#graph .node')).toHaveCount(3);
  await page.goto(base+'/extract?task='+taskId);
  await expect(page.locator('#ex-files')).toBeEnabled();
  await page.locator('#ex-files').setInputFiles({name:'bad.exe',mimeType:'application/octet-stream',buffer:Buffer.from('invalid')});await expect(page.locator('#ex-input-feedback')).toContainText('Markdown');await expect(page.locator('#ex-input-feedback')).toBeInViewport();
  await mkdir(resolve('.qa/extraction-ui'),{recursive:true});await page.screenshot({path:resolve('.qa/extraction-ui/desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.locator('#ex-start').click();await expect(page.locator('#ex-run-feedback')).toContainText('本修订已提交');await expect(page.locator('#ex-run-feedback')).toBeInViewport();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:resolve('.qa/extraction-ui/mobile.png'),fullPage:true});await page.getByRole('link',{name:'返回 AI 维护助手',exact:true}).click();
  await expect(page.locator('[data-scenario="paper"]')).toBeVisible();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:resolve('.qa/extraction-ui/assistant-mobile.png'),fullPage:true});
  await page.locator('.ai-batch-entry').click();
  await expect(page.locator('#ex-files')).toBeVisible();
  // Render an evidence-backed omission response without modifying the fixture task.
  const savedTask=await (await page.request.get(base+'/api/extraction/'+taskId)).json();
  const basisRef=Object.keys(savedTask.evidence)[0];
  await page.route('**/api/extraction/'+taskId, async route=>{
    if(route.request().method()!=='GET')return route.continue();
    const response={...savedTask,draft:{...savedTask.draft,deferred_items:['正文与结论存在差异（b_012abc）；需要核对。'],budget_omissions:[{title:'Similarity graph',reason:'Deferred within this test budget.',basis:[{ref:basisRef}]}]}};
    await route.fulfill({json:response});
  });
  await page.goto(base+'/extract?task='+taskId);
  await expect(page.locator('#ex-deferred')).toContainText('正文与结论存在差异；需要核对。');
  await expect(page.locator('#ex-deferred')).not.toContainText('b_012abc');
  await expect(page.locator('#ex-budget-omissions')).toContainText('Similarity graph');
  await expect(page.locator('#ex-budget-omissions a')).toHaveCount(1);
  const omittedSource=await page.locator('#ex-budget-omissions a').getAttribute('href');
  assert((await page.request.get(base+omittedSource)).ok());
  await page.locator('#ex-budget-results').scrollIntoViewIfNeeded();
  await page.screenshot({path:resolve('.qa/extraction-ui/budget-omissions-mobile.png')});
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#ex-max').scrollIntoViewIfNeeded();
  await page.screenshot({path:resolve('.qa/extraction-ui/budget-desktop.png')});
  assert.deepEqual(errors,[]);console.log('Extraction browser passed: mixed uploads, real review-gated proposals, shared graph, evidence links, duplicate submission errors, desktop/mobile.');
}finally{await browser?.close();child.kill('SIGTERM');}
